<!DOCTYPE html>
<html lang="fr">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Mon Journal Personnel</title>
    {{-- En dev, forcer une requête CSS explicite vers le server Vite pour faciliter le debug --}}
    @if (app()->environment('local'))
        <link rel="stylesheet" href="{{ env('VITE_DEV_SERVER_URL', 'http://localhost:5173') }}/resources/css/app.css">
    @endif
    {{-- Use the entries generated by Vite build (manifest) so Laravel can resolve assets reliably --}}
    @vite(['resources/css/app.css', 'resources/js/app.js'])
 <!-- point d'entrée Vue -->
</head>
<body>
    <div id="app"></div>
</body>
</html>
